const SESSION_ID = "SADIYA-MD=bh4gjKiK#mVRPjIzB0GuGilxwxMD4mxVaJzABVMO25ngcZ54N3ws"
const GITHUB_USER_NAME = "Kavindarashmina"
const GITHUB_AUTH_TOKEN = "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"
const DATABASE_REPO_NAME = "SADIYA-MD-DATABASE"

module.exports = {SESSION_ID,GITHUB_USER_NAME,GITHUB_AUTH_TOKEN,DATABASE_REPO_NAME}
